### ISSUE TITLE
setting up

### ISSUE THREAD

**Issue by nrc045** [peterzen/hass-pws-mqtt-addon#23]
Hello,
repositories added, 
addon installed and started, 
wh2600 found
sensor added in yaml

But no datas, and nothing in logfile
what did i missed ?

thank you very much for contribution and help

regards
NR

**Comment by nrc045** [comment]
in the addon log have the datas, but nothing is arriving on the mqtt server (mosquito), password probleme i think, is it possible to add it somewhere ?

**Comment by nrc045** [comment]
ok found problem, default topic in configuration and in yaml datas wa not the same now working 
great thx!

**Comment by peterzen** [comment]
Awesome, sorry for not replying sooner!

**Comment by peterzen** [comment]
Out of curiosity, what device are you using?

**Comment by nrc045** [comment]
conrad wh2600 ver 2.2.8

**Comment by nrc045** [comment]
uunique_id is almso missing in indoor temperature to have the sensor working

**Comment by peterzen** [comment]
> uunique_id is also missing in indoor temperature to have the sensor working

Fixed, thank you.
